### ISSUE TITLE
division is still broken

### ISSUE THREAD

**Issue by q3st1on** [9sqn/cryptocurrency#1]
It returns zero for numbers too big to handle (2 digits or more)

**Comment by 9sqn** [comment]
Division is now fully functional through the following process: binary search -> long division -> Goldschmidt division -> native division.

For numbers that are so big that they have to be handled by binary search, the division process takes some time (roughly 2 seconds for numbers of the size of Curve25519 points). I believe this is the case because multiplication isn’t fast enough
